### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by HowardvanRooijen** [unifiedfx/UFX.Relay#2]
We've got a similar scenario / use case, and we've been doing a research into various options- and was pleased to stumble upon the YARP thread which lead to this project. This looks really good and that we might be able to re-use some existing YARP middleware investments. So I just wanted to say thank-you for your efforts on this! 👏👏👏

I'll let you know how we get on once we've had a play.

**Comment by stephenwelsh** [comment]
Thanks for the feedback and let us know how you get on.
I've tried to keep the design of handling mapping the TunnelId as loose/simple as possible, if you have any scenario specific input that would be a great help to keep this flexible. Ideally we could have a few examples of implementing a few different scenarios.

**Comment by davidebbo** [comment]
Same as @HowardvanRooijen, I ended up here from https://github.com/microsoft/reverse-proxy/issues/1618. My scenario is a bit different (https://github.com/dotnet/aspire/issues/6547), but this still might fit.

**Comment by HowardvanRooijen** [comment]
We got our scenario working, and we're very happy with the result. Just mentioning @jamesdawson as he did most of the heavy lifting.

**Comment by davidebbo** [comment]
@HowardvanRooijen that's great! And nice to chat again, we used to connect way back in my Azure App Service days (10+ years ago?).

**Comment by HowardvanRooijen** [comment]
We did indeed! It's great to see you tinkering in this space again! Like minded people doing like minded things! We've been using this project to experiment with building a lightweight paas for high density multi tenant apps / untrusted workloads. Works really well.
