### ISSUE TITLE
What's the purpose of the Microsoft.VisualStudio.Threading reference?

### ISSUE THREAD

**Issue by HowardvanRooijen** [unifiedfx/UFX.Relay#4]
I noticed the `Microsoft.VisualStudio.Threading` dependency:

https://github.com/unifiedfx/UFX.Relay/blob/0d84c64cd6c1e7417f12ab9520dd64729bf8553b/src/UFX.Relay/UFX.Relay.csproj#L20

But I couldn't work out what is was for. 

I see that it's a dependency of `Nerdbank.Streams` - but don't understand why it's a specified reference, rather than just a transitory one.

I see it also gets a mention in the build: https://github.com/unifiedfx/UFX.Relay/actions/runs/11294387880/job/31414913852#step:5:16

Thanks!

**Comment by stephenwelsh** [comment]
Thanks for pointing out, looks like a rogue HintPath from the dev environment, I'll get it removed.

**Comment by stephenwelsh** [comment]
Thanks for the contribution @HowardvanRooijen, I've merged in your pull request and removed this HintPath now published to Nuget as version [0.2.1](https://www.nuget.org/packages/UFX.Relay/0.2.1)

**Comment by HowardvanRooijen** [comment]
Awesome! Thanks!
