### ISSUE TITLE
Sample not shutting down cleanly

### ISSUE THREAD

**Issue by davidebbo** [unifiedfx/UFX.Relay#5]
Cool project!

Running the sample unchanged, it works great, but the client seems to get stuck on shutdown (after Ctrl-C):

```
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

At that point, I have to hard kill Sample.Client.exe, e.g. by closing the window.

**Comment by stephenwelsh** [comment]
Thanks David, high praise indeed coming from yourself ;)

I have to give credit to [AArnott](https://github.com/AArnott) and his [MultiplexingStream](https://github.com/dotnet/Nerdbank.Streams/blob/main/doc/MultiplexingStream.md) project made the tunnel really simple to implement.

I'll have a look at the shutdown issue, if you have any other thoughts/suggestions on samples that would be great. There is scope for a few difference examples/scenarios but easy to overcomplicate.

**Comment by davidebbo** [comment]
Sounds good, I'll try to play with it in more depth in the next few days, and report any issues, thanks!

You probably didn't mean to close this issue, right?

**Comment by stephenwelsh** [comment]
Perfect, yeah, my bad.

**Comment by davidebbo** [comment]
Verified, thanks!

Hoping to play with my actual scenario today,
