### ISSUE TITLE
Adding UFX.Relay package brings in unwanted analyzers

### ISSUE THREAD

**Issue by davidebbo** [unifiedfx/UFX.Relay#6]
When I add UFX.Relay into my project, it has the side effect of bringing in `Microsoft.VisualStudio.Threading.Analyzers.*`, causing many analyzer errors that I can't easily address (huge project, many code owners).

I think this happens as a result of it using `Nerdbank.Streams`, which itself depends on some `Microsoft.VisualStudio.*`.

But that seems like strange behavior, if it means that any project using `Nerdbank.Streams` directly or indirectly is forced into those analyzers.

I couldn't find a way to disable them, other than disabling all analyzers on the project. Maybe this should be viewed as a `Nerdbank.Streams` issue?

**Comment by stephenwelsh** [comment]
I'll see if it's something that can be resolved in this project otherwise look to get Nerdbank.Streams updated.

**Comment by davidebbo** [comment]
I just found https://github.com/dotnet/Nerdbank.Streams/issues/516 and https://github.com/NuGet/Home/issues/6279. Seems it's a long standing nuget limitation, and it lists some workarounds. So probably not much you can do here.

**Comment by stephenwelsh** [comment]
Wow, no prospect of this getting fixed anytime soon then, it might be an option to copy in the parts of Nerdbank.Streams that this project uses as it has a lot of features we are not touching. Not ideal and may not help, but given the prospect of this being used in a large/complex project might be worth considering.

**Comment by davidebbo** [comment]
Turns out there is a solution to disable globally, so I think we can get by as it is: https://github.com/NuGet/Home/issues/6279#issuecomment-2450961895
